<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Route;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * RouteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RouteRepository extends EntityRepository
{
    public function __construct(EntityManagerInterface $em)
    {
        $md = new ClassMetadata(Route::class);
        parent::__construct($em, $md);
    }
}
