security:
    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        # To load users from somewhere else: http://symfony.com/doc/current/cookbook/security/custom_provider.html
        database_users:
            entity: { class: AppBundle:User, property: email }

    firewalls:
        secured_area:
            pattern: ^/

            access_denied_handler: AppBundle\Service\Security\AccessDenied

            anonymous: true

            form_login:
                check_path: security_login
                login_path: security_login
                csrf_token_generator: security.csrf.token_manager
                failure_handler: bundle.login.failure

            logout:
                path: security_logout
                target: index


    access_control: